-- ------------   TF (B1) - NBAGames   ------------
--
--                    SCRIPT DE CRIAÇÃO
--
-- Data Criacao ...........: 29/01/2023
-- Autor(es) ..............: Vinicius Assumpção de Araújo, Victor Hugo Oliveira Leão, Amanda Jennifer Pereira Nobre
-- Banco de Dados .........: MySQL 8.0
-- Base de Dados (nome) ...: NBAGames
--
--
-- PROJETO => 01 Base de Dados
--         => 05 Tabelas
--         => 01 View
--
-- ---------------------------------------------------------

CREATE DATABASE IF NOT EXISTS NBAGames;

USE NBAGames;

CREATE TABLE TEAMS(
	TEAM_ID            INTEGER     NOT NULL,
	MIN_YEAR           INTEGER     NOT NULL,
	MAX_YEAR           INTEGER     NOT NULL,
	ABBREVIATION       VARCHAR(6)  NOT NULL,
	NICKNAME           VARCHAR(20) NOT NULL,
	YEARFOUNDED        INTEGER     NOT NULL,
	CITY               VARCHAR(30) NOT NULL,
    ARENA              VARCHAR(50) NOT NULL,
    ARENACAPACITY      INTEGER,
	CONSTRAINT TEAMS_PK PRIMARY KEY(TEAM_ID),
    CONSTRAINT TEAMS_UK UNIQUE KEY(NICKNAME, ABBREVIATION)
) ENGINE = InnoDB;

CREATE TABLE RANKING(
	SEASON_ID     INTEGER  	  NOT NULL,
	STANDINGSDATE DATE  	  NOT NULL,
	CONFERENCE    VARCHAR(10) NOT NULL,
	G             INTEGER     NOT NULL,
	W             INTEGER     NOT NULL,
	L             INTEGER     NOT NULL,
	TEAM_ID       INTEGER     NOT NULL,
    CONSTRAINT RANKING_TEAM_FK FOREIGN KEY(TEAM_ID)
    REFERENCES TEAMS(TEAM_ID)
)ENGINE = InnoDB;


CREATE TABLE PLAYERS(
	PLAYER_ID   INTEGER     NOT NULL,
	PLAYER_NAME VARCHAR(50) NOT NULL,
	SEASON      INTEGER     NOT NULL,
	TEAM_ID     INTEGER     NOT NULL,
	CONSTRAINT PLAYERS_PK PRIMARY KEY(PLAYER_ID),
	CONSTRAINT PLAYERS_TEAMS_FK FOREIGN KEY(TEAM_ID)
	REFERENCES TEAMS(TEAM_ID)
)ENGINE = InnoDB;

CREATE TABLE GAMES(
	GAME_ID          INTEGER  		NOT NULL,
	GAME_DATE_EST    DATE  			NOT NULL,
    GAME_STATUS_TEXT VARCHAR(50)    NOT NULL,
    HOME_TEAM_ID     INTEGER  		NOT NULL,
    SEASON           INTEGER  		NOT NULL,
    PTS_home         NUMERIC(5,1),
    FG_PCT_home      NUMERIC(5,1),
    FT_PCT_home      NUMERIC(5,1),
    FG3_PCT_home     NUMERIC(5,1),
    AST_home         NUMERIC(4,1),
    REB_home         NUMERIC(4,1),
	VISITOR_TEAM_ID  INTEGER  		NOT NULL,
    PTS_away         NUMERIC(5,1),
    FG_PCT_away      NUMERIC(5,1),
    FG3_PCT_away     NUMERIC(5,1),
    AST_away         NUMERIC(4,1),
    REB_away         NUMERIC(4,1),
    HOME_TEAM_WINS   BIT  			NOT NULL,
	CONSTRAINT GAMES_PK PRIMARY KEY(GAME_ID)
)ENGINE = InnoDB;

CREATE TABLE GAME_DETAILS (
	GAME_ID 	   INT    DEFAULT NULL,
	PLAYER_ID 	   INT    DEFAULT NULL,
	START_POSITION TEXT   DEFAULT NULL,
	MIN 		   TEXT   DEFAULT NULL,
	FGM 		   DOUBLE DEFAULT NULL,
	FGA 		   DOUBLE DEFAULT NULL,
	FG3M 		   DOUBLE DEFAULT NULL,
	FG3A 		   DOUBLE DEFAULT NULL,
	FTM 		   DOUBLE DEFAULT NULL,
	FTA 		   DOUBLE DEFAULT NULL,
	OREB 		   DOUBLE DEFAULT NULL,
	DREB 		   DOUBLE DEFAULT NULL,
	REB 		   DOUBLE DEFAULT NULL,
	AST 		   DOUBLE DEFAULT NULL,
	STL 		   DOUBLE DEFAULT NULL,
	BLK 		   DOUBLE DEFAULT NULL,
	PF 			   DOUBLE DEFAULT NULL,
	PTS 		   DOUBLE DEFAULT NULL,
	PLUS_MINUS 	   TEXT   DEFAULT NULL,
	CONSTRAINT GAMES_DETAILS_GAMES_FK FOREIGN KEY(GAME_ID)
	REFERENCES GAMES(GAME_ID),
    CONSTRAINT GAMES_DETAILS_PLAYERS_FK FOREIGN KEY(PLAYER_ID)
	REFERENCES PLAYERS(PLAYER_ID)
) ENGINE=InnoDB